name: demopatient
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+11
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  date_picker_timeline: ^1.2.1
  fluttertoast: ^7.0.2
  table_calendar: ^2.2.3
  pin_code_fields: ^6.0.2
  country_calling_code_picker: ^1.0.8+1
  cached_network_image: ^2.5.1
  url_launcher: ^6.0.3
  firebase_auth: ^1.0.1
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^5.0.0+1
  cloud_firestore: ^1.0.1
  http: ^0.13.1
  flutter_svg: ^0.22.0
  flutter_quill: ^1.2.2
  swipedetector: ^1.2.0
  shared_preferences: ^2.0.5
  share: ^0.6.5+4
  multi_image_picker: ^4.8.0
  flutter_absolute_path: ^1.0.6
  flutter_downloader: ^1.6.0
  path_provider: ^2.0.1
  permission_handler: ^8.0.0+2
  package_info: ^2.0.2
  device_apps: ^2.1.1
  razorpay_flutter: ^1.2.7
  http_auth: ^1.0.1
  webview_flutter: ^2.0.1
  jitsi_meet: ^4.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/icon/whatsapp.png
    - assets/icon/dr.png
    - assets/images/map.png
    - assets/images/map3.jpg
    - assets/icon/teeth.svg
    - assets/icon/gallery.svg
    - assets/icon/appoin.svg
    - assets/icon/doct.svg
    - assets/icon/sch.svg
    - assets/icon/chat.svg
    - assets/icon/bell.svg
    - assets/icon/call.svg
    - assets/icon/reachus.svg
    - assets/icon/nodata.svg
    - assets/icon/error.svg
    - assets/icon/booking.svg
    - assets/icon/type.svg
    - assets/icon/docblog.svg
    - assets/icon/editProfile.svg
    - assets/images/online.jpg
    - assets/images/offline.jpg
    - assets/icon/dprofile.png
    - assets/icon/pres.svg
    - assets/icon/user.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/CM Sans Serif.ttf

    - family: OpenSans-SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: OpenSans-ExtraBoldItalic
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
